apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1cd4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1cd4
    app.kubernetes.io/part-of: ci1t-43256-0045-app
  name: devfile-sample-1cd4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1cd4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1cd4
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0045-tenant/ci1t-43256-0045-app/devfile-sample-1cd4@sha256:63dbb266a63ec77d035b7a9205adc4714e007958503886e480084db8f9c5f724
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
